Repository GoogleCloudPlatform/fda-mystudies, pull requests merged in 2021-06, with the labels that each got.

#3661 [v2.0.6] Issue #3627, #3633
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: cla: yes

#3647 [v2.0.6] Fixed issues oauth server 3204, study builder 3643
  auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/LoginController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
Labels: cla: yes

#3692 [v2.0.6] Issue #3677 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: cla: yes

#3681 [v2.0.6]-issues fixed-#3489, #3488, #3487, #3484, #3483, #3477, #3474, #3472, #3471
  participant-manager/src/app/site-coordinator/account/account-profile/account-profile.component.html
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
  participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.html
  participant-manager/src/assets/css/theme-layout.scss
Labels: cla: yes

#3702 [v2.0.6] - Fixed issue #3607 and #3626
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ErrorCode.java
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/LocationRepository.java
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/SiteRepository.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/LocationServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/task/ChangeDefaultLocation.java
  participant-manager/src/app/shared/error.codes.enum.ts
Labels: Participant manager, Participant manager datastore, cla: yes

#3703 [v2.0.6] Issue #3651 #3652 #3690 fixed
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
Labels: cla: yes

#3668 [v2.0.6] Dependency issue fixes
  auth-server/oauth-scim-service/pom.xml
  common-modules/common-tests/pom.xml
  participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
  participant-manager-datastore/participant-manager-service/pom.xml
  study-builder/fdahpStudyDesigner/pom.xml
  study-datastore/pom.xml
Labels: cla: yes

#3704 [v2.0.6] Study builder, Issues fixed 3685 3653
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css
Labels: cla: yes

#3732 [v2.0.6] - Fixed issue #3718,#3684,#3709
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp
Labels: Study builder, cla: yes

#3726 [v2.0.6] Fixed issue #3686 [SB] Active task > Add to chart > Values in the 'Time range for the chart' dropdown getting duplicated
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: cla: yes

#3730 [v2.0.6] Issue 3628 fixes
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
Labels: cla: yes

#3729 [v2.0.6] iOS-Fixed issue # 3568 - Notification
  iOS/MyStudies/MyStudies/Networking/APIs/UserServices.swift
Labels: cla: yes

#3738 [v2.0.6] iOS-Fixed issue # 3580
  iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift
Labels: cla: yes

#3746 [v2.0.6] Issue #3719 #3737 #3700 fixed
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3736 [v2.0.6] - Android - fixes for #3509
  Android/app/build.gradle
  Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoPagerAdapter.java
  Android/app/src/main/java/com/harvard/studyappmodule/StudyListAdapter.java
Labels: cla: yes

#3748 [v2.0.6] - #3482, #3481, #3479, #3475,#3472, #3342 issue resolved
  participant-manager/package-lock.json
  participant-manager/src/app/site-coordinator/apps/app-details/app-details.component.html
  participant-manager/src/app/site-coordinator/location/location-list/location-list.component.html
  participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.html
  participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.ts
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.scss
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.html
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.scss
  participant-manager/src/app/site-coordinator/studies/study-details/study-details.component.html
  participant-manager/src/app/site-coordinator/user/new-user/new-user.component.html
  participant-manager/src/app/site-coordinator/user/new-user/new-user.component.scss
  participant-manager/src/app/site-coordinator/user/new-user/new-user.component.ts
  participant-manager/src/app/site-coordinator/user/update-user/update-user.component.scss
  participant-manager/src/app/site-coordinator/user/user-details/user-details.component.html
  participant-manager/src/app/site-coordinator/user/user-details/user-details.component.scss
  participant-manager/src/app/site-coordinator/user/user-details/user-details.component.ts
  participant-manager/src/app/site-coordinator/user/user-list/user-list.component.html
  participant-manager/src/assets/css/root.scss
  participant-manager/src/assets/css/theme-layout.scss
Labels: cla: yes

#3752 [v2.0.6] - Fixed issue #3745
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js
Labels: Study builder, cla: yes

#3749 [v2.0.6] - Issue 3739 fixes
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
Labels: cla: yes

#3765 [v2.0.6] iOS-Fixed issue # 3731
  iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift
  iOS/MyStudies/MyStudies/Views/Steps/ConsentStep/ConsentStep.swift
Labels: cla: yes

#3763 [v2.0.6] iOS-Fixed issue # 3404
  iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/ChartsUI/ChartsViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyDashboardUI/StudyDashboardViewController.swift
Labels: cla: yes

#3758 [v2.0.6] Fixed issue #3751
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
Labels: cla: yes

#3759 [v2.0.6] Issue #3750 fixed
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
Labels: cla: yes

#3756 [v2.0.6] Fixed issue #3743
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3776 [v2.0.6] [SB] Provision for import/export and replication of studies
  deployment/mystudies.hcl
  deployment/terraform/kubernetes/main.tf
  study-builder/fdahpStudyDesigner/pom.xml
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/ActiveTaskCustomScheduleBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/ActiveTaskFrequencyBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/ComprehensionTestResponseBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/NotificationBO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/QuestionResponseSubTypeBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/QuestionnaireBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/QuestionnaireCustomScheduleBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/QuestionnairesFrequenciesBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/StudyPageBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/StudyBuilderAuditEvent.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/IdGenerator.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/StudyExportSqlQueries.java
  study-builder/fdahpStudyDesigner/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyControllerTest.java
  study-builder/tf-deployment.yaml
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
Labels: cla: yes

#3768 [v2.0.6] Fixed issue #3494
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
Labels: cla: yes

#3771 [v2.0.6] Issue #3762 fixed
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
Labels: cla: yes

#3778 [v2.0.6] Issue #3772, #3777 and #3766 fixed
  participant-manager/src/app/site-coordinator/apps/app-details/app-details.component.html
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
  participant-manager/src/assets/css/utilities.scss
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3784 [v2.0.6] Fixed issue #3782
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: Study builder, cla: yes

#3779 [V2.0.6] Android - #3744 & #3747
  Android/app/src/main/java/com/harvard/studyappmodule/CustomActivitiesDailyDialogClass.java
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesListAdapter.java
Labels: cla: yes

#3780 [V2.0.6] Android - #3494
  Android/app/src/main/java/com/harvard/WebViewActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/ResourcesWebViewActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoPagerAdapter.java
  Android/app/src/main/java/com/harvard/studyappmodule/consent/ConsentBuilder.java
  Android/app/src/main/java/com/harvard/studyappmodule/consent/CustomConsentViewTaskActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/consent/consentsharingstepcustom/LoadMoreActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/custom/question/InstructionStepLayoutCustom.java
Labels: cla: yes

#3781 [v2.0.6] iOS-Fixed issue # 2447
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyDashboardUI/StudyDashboardViewController.swift
  iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
  iOS/MyStudies/MyStudies/Models/ScheduleModel/Schedule.swift
Labels: cla: yes

#3790 [v2.0.6] Db issue fixed
  db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/ApplicationContext.xml
Labels: cla: yes

#3795 [v2.0.6] Fixed Issue #3792
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
Labels: cla: yes

#3794 [v2.0.6] Fixed Issue #3787 #3788 #3791
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/CustomSuccessHandler.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/copyright.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
Labels: cla: yes

#3785 [v2.0.6] Fixed issue 2447 Add ability to specify separate start and end times for custom schedule
  db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/test/resources/import.sql
  study-datastore/pom.xml
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/DashboardMetaDataDao.java
Labels: cla: yes

#3798 [v2.0.6] Fixed issues #3797 #3741 study builder active tasks custom schedule
  db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
Labels: cla: yes

#3804 [v2.0.6] Fixed issue #3788 #3793
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
Labels: cla: yes

#3801 [v2.0.6] iOS-Fixed issue # 3716
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyDashboardUI/StudyDashboardViewController.swift
  iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
  iOS/MyStudies/MyStudies/Networking/APIs/ResponseServices.swift
Labels: cla: yes

#3805 [v2.0.6] Fixed issue #3796
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
Labels: cla: yes

#3810 [v2.0.6] Fixed issue #3682
  study-datastore/src/main/java/com/hphc/mystudies/dao/DashboardMetaDataDao.java
Labels: cla: yes

#3814 [v2.0.6] Fixed issue #3807
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-datastore/src/main/java/com/hphc/mystudies/dto/StudyPageDto.java
Labels: cla: yes

#3808 [v2.0.6] Fixed issue 3803
  study-datastore/pom.xml
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
Labels: cla: yes

#3806 [v2.0.6] Fixed issue #3770 and #3775
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.scss
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.html
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.scss
Labels: cla: yes

#3820 [v2.0.6] Fixed issue #3817
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/DashBoardAndProfileController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
Labels: cla: yes

#3822 [v2.0.6] Fixed Issue #3812 #3813
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
Labels: cla: yes

#3827 [v2.0.6] iOS-Fixed issue #3186
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/ProfileViewUI/ProfileViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/SlideMenu/LeftMenuViewController.swift
  iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/GatewayOverviewUI/HomeViewController.swift
Labels: cla: yes

#3825 [v2.0.6] iOS-Fixed issue #3815
  iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift
Labels: cla: yes

#3830 [v2.0.6] Fixed issue #3829 [SB] Clicking on 'Actions' study zone section navigating to studies list and hence unable to perform any actions
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
Labels: cla: yes

#3834 [v2.0.6] Fixed issue #3824 #3828
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
Labels: cla: yes

#3831 [V2.0.6] Android - #3495
  Android/app/build.gradle
Labels: cla: yes

#3832 [V2.0.6] Android - #3509
  Android/app/src/main/java/com/harvard/studyappmodule/StudyListAdapter.java
Labels: cla: yes

#3821 [v2.0.6] Fixed issue #3802
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java
Labels: cla: yes

#3836 [2.0.6] Fixed issue #3833
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
Labels: cla: yes

#3837 [v2.0.6] Fixed issue #3835
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java
Labels: cla: yes
