Repository GoogleCloudPlatform/fda-mystudies, pull requests merged in 2021-02, with the labels that each got.

#3083 Study Builder: Fixed issue #562
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3085 Study Builder: Fixed #3049 #3050
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/copyright.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css
Labels: cla: yes

#3081 Study Builder: Fixed issue #2919
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3086 [SB] Custom schedule frequency > Time field is disabled in a scenario…
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3084 Study Builder : Fixed issue #2929, Revise text across screens
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
Labels: cla: yes

#3087 Android - minor text changes
  Android/app/src/main/res/values/strings.xml
Labels: cla: yes

#3078 [Study Builder]: Issue 3060 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
Labels: cla: yes

#3075 [Study Builder]: Issue 3040 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyQuestionnaireControllerTest.java
  study-builder/fdahpStudyDesigner/src/test/resources/import.sql
Labels: cla: yes

#3068 PM web app issue #1415, #3033, #2145 and #3029 fixed
  participant-manager/src/app/auth/set-up-account/set-up-account.component.html
  participant-manager/src/app/auth/set-up-account/set-up-account.component.ts
  participant-manager/src/app/service/auth.service.ts
  participant-manager/src/app/site-coordinator/account/account-profile/account-profile.component.html
  participant-manager/src/app/site-coordinator/user/new-user/new-user.component.html
  participant-manager/src/app/site-coordinator/user/update-user/update-user.component.html
Labels: cla: yes

#3056 Create repo-sync.yml
  .github/workflows/repo-sync.yml
Labels: cla: yes

#3111 Updated readme.md file for study builder and oauth server
  auth-server/README.md
  auth-server/oauth-scim-service/src/main/resources/static/images/landingpage-logo.png
  auth-server/oauth-scim-service/src/main/resources/templates/login.html
  study-builder/README.md
Labels: cla: yes

#3110 Pm webapp issue 2317 fixing
  participant-manager/README.md
Labels: cla: yes

#3103 Pm web app terraform build failing fixed
  participant-manager/src/app/http-interceptors/auth.interceptor.ts
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.spec.ts
  participant-manager/src/app/site-coordinator/sites/import-email-list/import-email-list.component.ts
Labels: cla: yes

#3109 PM-webapp - #3104 fixed
  participant-manager/src/app/about/about.component.html
  participant-manager/src/app/error/error.component.html
  participant-manager/src/app/page-not-found/page-not-found.component.html
  participant-manager/src/app/terms/terms.component.html
Labels: cla: yes

#3107 Study Builder : Fixed issue #2929, Revise text across screens
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
Labels: cla: yes

#3102 [Participant-Datastore]: Issue 3095 fixes
  common-modules/common-tests/src/main/resources/mappings/response-service/response-server-deactivate.json
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserManagementProfileServiceImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/UserManagementUtil.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileControllerTest.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/resources/data.sql
Labels: cla: yes

#3100 [SB] Issue #3094 fixed, User is not able to create activities with Anchor date based schedule type and custom schedule frequency
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3126 PM webapp issue #3116 & #3118 - fixed.
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.html
  participant-manager/src/assets/css/root.scss
Labels: cla: yes

#3127 [SB] Issue 3120 fixed , Unable to create 'Tower of Hanoi' active task with Custom schedule
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: cla: yes

#3129 [SB] issue #3119 -Unable to delete active tasks
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
Labels: cla: yes

#3134 Deployment scripts update
  auth-server/tf-deployment.yaml
  deployment/README.md
  deployment/deployment.hcl
  deployment/kubernetes/README.md
  deployment/kubernetes/cert.yaml
  deployment/kubernetes/ingress.yaml
  deployment/mystudies.hcl
  deployment/scripts/create_study_builder_superadmin.sh
  deployment/scripts/register_clients_in_hydra.sh
  deployment/scripts/set_env_var.sh
  hydra/tf-deployment.yaml
  participant-datastore/consent-mgmt-module/tf-deployment.yaml
  participant-datastore/enroll-mgmt-module/tf-deployment.yaml
  participant-datastore/user-mgmt-module/tf-deployment.yaml
  participant-manager-datastore/tf-deployment.yaml
  participant-manager/Dockerfile
  participant-manager/src/environments/environment.prod.ts
  participant-manager/tf-deployment.yaml
  participant-manager/tf-service.yaml
  response-datastore/tf-deployment.yaml
  study-builder/tf-deployment.yaml
  study-datastore/tf-deployment.yaml
Labels: Deployment, cla: yes

#3138 Deployment scripts update
  .github/workflows/repo-sync.yml
  deployment/scripts/create_participant_manager_superadmin.sh
  deployment/scripts/set_env_var.sh
Labels: Deployment, cla: yes

#3142 Fixed issues #3121 #3137 #3139, study builder settings, Add/Edit questionnaire
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
Labels: cla: yes

#3144 Pin k8s provider version
  deployment/mystudies.hcl
  deployment/terraform/kubernetes/main.tf
Labels: cla: yes

#3145 Update cloudbuild.yaml
  participant-manager/cloudbuild.yaml
Labels: cla: yes

#3163 PM web app Formatting issue fixed
  participant-manager/src/environments/environment.prod.ts
Labels: cla: yes

#3162 [Study Datastore]Issue #3158 , #3159 - Studies which are configured for only Android in SB are not displaying in android mobile application
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java
Labels: cla: yes

#3179 New GKE cluster Isitio system Pods issue
  deployment/mystudies.hcl
Labels: Deployment, cla: yes

#3232 [v2.0.3][Study Builder]Allow Right Click across application
  study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js
Labels: cla: yes

#3230 [v2.0.3] [Participant Manager Datastore] XSS issue fix
  common-modules/common-service/pom.xml
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/CleanPropertyAdvice.java
Labels: cla: yes

#3206 [v2.0.3] [SB]: Fixed issue #3037 #2965
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3213 [v2.0.3] : Fixed issue #3077 #3133
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
Labels: Study builder, cla: yes

#3202 [v2.0.3] Database Migrations with Flyway
  db-migration/auth-server-db-migration/.gitignore
  db-migration/auth-server-db-migration/db/migration/V2_0_3__release.sql
  db-migration/auth-server-db-migration/flyway.properties
  db-migration/auth-server-db-migration/pom.xml
  db-migration/participant-datastore-db-migration/.gitignore
  db-migration/participant-datastore-db-migration/db/migration/V2_0_3__release.sql
  db-migration/participant-datastore-db-migration/flyway.properties
  db-migration/participant-datastore-db-migration/pom.xml
  db-migration/response-datastore-db-migration/.gitignore
  db-migration/response-datastore-db-migration/db/migration/V2_0_3__release.sql
  db-migration/response-datastore-db-migration/flyway.properties
  db-migration/response-datastore-db-migration/pom.xml
  db-migration/study-builder-db-migration/.gitignore
  db-migration/study-builder-db-migration/db/migration/V2_0_3__release.sql
  db-migration/study-builder-db-migration/flyway.properties
  db-migration/study-builder-db-migration/pom.xml
Labels: cla: yes

#3238 [v2.0.3]Issue #3151 fixes
  common-modules/common-tests/src/main/resources/mappings/enroll-service/withdraw_emptyParticipantId_failure.json
  common-modules/common-tests/src/main/resources/mappings/enroll-service/withdraw_emptyStudyId_failure.json
  common-modules/common-tests/src/main/resources/mappings/enroll-service/withdraw_failureCase.json
  common-modules/common-tests/src/main/resources/mappings/enroll-service/withdraw_success.json
  common-modules/common-tests/src/main/resources/mappings/response-service/response-server-deactivate.json
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/WithdrawFromStudyBean.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/StudyStateController.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/StudyStateDao.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/StudyStateDaoImpl.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyStateService.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyStateServiceImpl.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/EnrollmentManagementUtil.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/tests/StudyStateControllerTest.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/bean/StudyReqBean.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/DeactivateAcctBean.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/WithdrawFromStudyBean.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/common/UserMgmntEvent.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserManagementProfileServiceImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/UserManagementUtil.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileControllerTest.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ResponseServerEvent.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/ProcessActivityResponseController.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/ActivityResponseProcessorService.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/ActivityResponseProcessorServiceImpl.java
  response-datastore/response-server-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/ProcessActivityResponseControllerTest.java
Labels: Participant datastore, Response datastore, cla: yes

#3215 [v2.0.3] Fixed Issue #3072 #3136 #3141
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibiltyTest.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
Labels: Study builder, cla: yes

#3240 [v2.0.3] Issue #3181 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/images/logo/logo_innerScreens.png
  study-builder/fdahpStudyDesigner/src/main/webapp/images/logo/logo_landing_welcome.png
Labels: Study builder, cla: yes

#3234 [v2.0.3] Fixed Issue #3169
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
Labels: Study builder, cla: yes

#3228 [v2.0.3] Fixed Issue #3035 #3053 #3123
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/403.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/404.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/errorPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/css/sprites_v3.css
Labels: Study builder, cla: yes

#3209 [v2.0.3] : Fixed issue #3140 and #3112
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
Labels: Study builder, cla: yes

#3214 [v2.0.3] [StudyBuilder] issue #3122 #3135 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
Labels: Study builder, cla: yes

#3236 [v2.0.3] Fixed Issue #2913 #3171 #3190
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
Labels: cla: yes

#3226 [v2.0.3] Pm webapp issue 2648 fixing
  participant-manager/src/app/auth/set-up-account/set-up-account.component.html
  participant-manager/src/app/site-coordinator/account/account-profile/account-profile.component.html
  participant-manager/src/app/site-coordinator/location/add-location/add-location.component.html
  participant-manager/src/app/site-coordinator/location/edit-location/edit-location.component.html
  participant-manager/src/app/site-coordinator/sites/add-email/add-email.component.html
  participant-manager/src/app/site-coordinator/user/new-user/new-user.component.html
  participant-manager/src/app/site-coordinator/user/update-user/update-user.component.html
Labels: cla: yes

#3216 [v2.0.3] Fixed Issue #2333 Set toast display timers to 5 seconds
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/emailChangeVerificationPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js
Labels: Study builder, cla: yes

#3220 [v2.0.3] #3180 [SB] Study settings section
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
Labels: Study builder, cla: yes

#3227 [v2.0.3] Fixed issue #1150 [Android] Continuous loading animator and fails to navigate to app when internet is disrupted during sign-in
  auth-server/oauth-scim-service/src/main/resources/static/css/style.css
  auth-server/oauth-scim-service/src/main/resources/static/js/autoLogin.js
  auth-server/oauth-scim-service/src/main/resources/static/js/consent.js
  auth-server/oauth-scim-service/src/main/resources/templates/autoLogin.html
  auth-server/oauth-scim-service/src/main/resources/templates/consent.html
Labels: Android, Auth server, cla: yes

#3235 [v2.0.3] Fixed issue #3105 [SB] Questionnaires/Active tasks > Issue in custom schedule
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3251 [v2.0.3] Fixed issue #562 Start time cannot be specified for activity with custom schedule
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3252 [v2.0.3] fixed issue #3225
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3210 [v2.0.3] [Study Builder] issues #3098 #3168 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
Labels: Study builder, cla: yes

#3229 [v2.0.3] Issue #3178 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: Study builder, cla: yes

#3211 [v2.0.3] PM-webapp-site/study/app permission #2547 issue fixed
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.html
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.scss
Labels: Participant manager, cla: yes

#3250 [v2.0.3]-SB-fixed-#3161-#3157-#3156-#3155-#2887
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css
  study-builder/fdahpStudyDesigner/src/main/webapp/images/icons/edit_draft_icon__hover.png
  study-builder/fdahpStudyDesigner/src/main/webapp/images/icons/edit_icn__hover.png
  study-builder/fdahpStudyDesigner/src/main/webapp/images/icons/live_icn__hover.png
Labels: cla: yes

#3254 [v2.0.3] Fixed Issue #3205
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
Labels: cla: yes

#3217 [v2.0.3]: Fixed issue #3124
  participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/UserEnrollmentTokenMgmtServiceWsApplication.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AppConfig.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AuthenticationEntryPointImpl.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/BeanConfig.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/WebSecurityConfig.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/resources/log4j2.xml
Labels: Participant datastore, cla: yes

#3249 [v2.0.3] Fixed Issue #3233
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
Labels: cla: yes

#3222 [v2.0.3]: Fixed issue #3165 #3160
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/NotificationController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
Labels: Study builder, cla: yes

#3212 [v2.0.3] Fixed Issue #1868: In consistency in the email formate
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/UserRegistrationForm.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserRegistrationController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserManagementProfileService.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserManagementProfileServiceImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserRegistrationServiceImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileControllerTest.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserRegistrationControllerTest.java
Labels: Participant datastore, cla: yes

#3257 [v2.0.3]: Fixed issue #3153
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/StudyBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/StudyBuilderAuditEvent.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
  study-datastore/src/main/java/com/hphc/mystudies/bean/SettingsBean.java
  study-datastore/src/main/java/com/hphc/mystudies/bean/StudyInfoResponse.java
  study-datastore/src/main/java/com/hphc/mystudies/bean/WithdrawalConfigBean.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dto/StudyDto.java
Labels: Study builder, Study datastore, cla: yes

#3218 [v2.0.3] [Consent Module] Fixed Issue #3124
  participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/MyStudiesUserRegWsApplication.java
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AppConfig.java
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AuthenticationEntryPointImpl.java
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/BeanConfig.java
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/WebSecurityConfig.java
Labels: Participant datastore, cla: yes

#3256 [v2.0.3]: Fixed issue #936 #3113 Revise roles managed via UI
  db-migration/study-builder-db-migration/db/migration/V2_0_3__release.sql
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/UsersController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/UsersControllerTest.java
Labels: Study builder, cla: yes

#3198 [v2.0.3] Issue 3093 fixes
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/EnrollmentTokenController.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/ErrorResponseUtil.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/tests/EnrollmentTokenControllerTest.java
Labels: Participant datastore, cla: yes

#3223 [v2.0.3] Issue 3124 fixes
  response-datastore/response-server-service/pom.xml
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AppConfig.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AuthenticationEntryPointImpl.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/WebSecurityConfig.java
Labels: cla: yes

#3219 [v2.0.3][User Management Service] Fixed issue #3124
  participant-datastore/user-mgmt-module/user-mgmt/pom.xml
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AppConfig.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AuthenticationEntryPointImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/BeanConfig.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/WebSecurityConfig.java
Labels: Participant datastore, cla: yes

#3237 [v2.0.3] Issue 3115 fixes
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/model/StudyEntity.java
  db-migration/participant-datastore-db-migration/db/migration/V2_0_3__release.sql
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/bean/StudyMetadataBean.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/StudiesDaoImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/StudiesControllerTest.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/testutils/Constants.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/bean/StudyMetadataBean.java
  response-datastore/response-server-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/StudyMetadataControllerTest.java
  response-datastore/response-server-service/src/test/java/com/google/cloud/healthcare/fdamystudies/utils/Constants.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bean/StudyDetailsBean.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
Labels: Participant datastore, Participant manager datastore, Response datastore, Study builder, cla: yes

#3208 [v2.0.3] #1448 , #3001 , #2644 and #3089 issue fixes
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/WebSecurityConfig.java
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.ts
  participant-manager/src/app/site-coordinator/studies/study-details/study-details.component.ts
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
Labels: Participant manager, Study builder, cla: yes

#3258 [v2.0.3] Fixed Issue #3248
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
Labels: Study builder, cla: yes

#3231 [v2.0.3][Study Builder]HTML breakage for special characters
  study-builder/fdahpStudyDesigner/pom.xml
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/CleanPropertyAdvice.java
Labels: cla: yes

#3221 [v2.0.3] Fixed issue #2998, Retain Sites page when user clicks on load more icon and adds a site
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/SiteResponse.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/mapper/SiteMapper.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
  participant-manager/src/app/entity/mock-studies-data.ts
  participant-manager/src/app/site-coordinator/sites/add-site/add-site.component.ts
  participant-manager/src/app/site-coordinator/sites/shared/sites.service.ts
  participant-manager/src/app/site-coordinator/sites/site-list/site-list.component.html
  participant-manager/src/app/site-coordinator/sites/site-list/site-list.component.ts
  participant-manager/src/app/site-coordinator/studies/shared/site.model.ts
Labels: Participant manager, Participant manager datastore, cla: yes

#3242 [v2.0.3] Android - fixes for #3146
  Android/app/src/main/java/com/harvard/studyappmodule/consent/ConsentBuilder.java
  Android/app/src/main/res/values/strings.xml
Labels: cla: yes

#3243 [v2.0.3] Android - fixes for #3147
  Android/app/src/fda/java/com/harvard/studyappmodule/StudyActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/NotificationListAdapter.java
  Android/app/src/main/java/com/harvard/studyappmodule/ResourcesListAdapter.java
  Android/app/src/main/java/com/harvard/studyappmodule/StandaloneActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/StandaloneStudyInfoActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/StudyListAdapter.java
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivity.java
  Android/app/src/main/java/com/harvard/usermodule/LoginCallbackActivity.java
  Android/app/src/main/res/values/strings.xml
Labels: cla: yes

#3244 [v2.0.3] Android - fixes #3148
  Android/app/src/main/java/com/harvard/studyappmodule/DeleteAccountActivity.java
  Android/app/src/main/java/com/harvard/studyappmodule/ResourcesListAdapter.java
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyResourcesFragment.java
  Android/app/src/main/res/values/strings.xml
Labels: cla: yes

#3245 [v2.0.3] Android - fixes for #3184
  Android/app/src/fda/res/drawable-560dpi/logo1.png
  Android/app/src/fda/res/drawable-560dpi/logo2.png
  Android/app/src/fda/res/drawable-xhdpi/logo1.png
  Android/app/src/fda/res/drawable-xhdpi/logo2.png
  Android/app/src/fda/res/drawable-xxhdpi/logo1.png
  Android/app/src/fda/res/drawable-xxhdpi/logo2.png
  Android/app/src/fda/res/drawable-xxxhdpi/logo1.png
  Android/app/src/fda/res/drawable-xxxhdpi/logo2.png
  Android/app/src/main/res/layout/gateway_item1.xml
Labels: cla: yes

#3262 Stack Driver logging client not shut down properly issue fix
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/AuditEventServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/AuditEventServiceImpl.java
  study-datastore/src/main/java/com/hphc/mystudies/service/AuditEventService.java
Labels: cla: yes

#3263 [Study Datastore] validate apptoken and bundleid belongs to same platform type
  study-datastore/src/main/java/com/hphc/mystudies/web/servlet/AuthenticationService.java
Labels: cla: yes

#3271 [v2.0.3] Fixed issue #2646, Password Strength Meter
  participant-manager/src/app/_helper/validator.ts
  participant-manager/src/app/auth/set-up-account/set-up-account.component.html
  participant-manager/src/app/auth/set-up-account/set-up-account.component.scss
  participant-manager/src/app/auth/set-up-account/set-up-account.component.ts
  participant-manager/src/app/shared/error.codes.enum.ts
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.scss
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.ts
  participant-manager/src/styles.scss
Labels: cla: yes

#3265 [v2.0.3] Fixed issue #3264 [SB] Unable to schedule the the Questionnaries in the study
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3275 [v2.0.3] Fixed issue #3183 [Auth server] Replace the current logo with revised image
  auth-server/oauth-scim-service/src/main/resources/static/images/landing-logo.png
  auth-server/oauth-scim-service/src/main/resources/static/images/landingpage-logo.png
  auth-server/oauth-scim-service/src/main/resources/templates/login.html
Labels: Auth server, cla: yes

#3241 [v2.0.3] Issue 2606 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/StudyBuilderAuditEvent.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/StudyBuilderAuditEventHelper.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/LoginController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/UsersController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/EmailNotification.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/common/BaseMockIT.java
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyQuestionnaireControllerTest.java
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/UsersControllerTest.java
  study-builder/fdahpStudyDesigner/src/test/resources/application-mockit.properties
  study-builder/fdahpStudyDesigner/src/test/resources/import.sql
Labels: Study builder, cla: yes

#3269 [v2.0.3] Issue 3247 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
Labels: cla: yes
