Repository GoogleCloudPlatform/fda-mystudies, pull requests merged in 2021-03, with the labels that each got.

#3224 [v2.0.3] Fixed Issue #3164 #3187 #3167
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/LoginController.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/LoginControllerTest.java
Labels: cla: yes

#3274 [v2.0.3]: Fixed issue #3113 Updated V2_0_3__release.sql script
  db-migration/study-builder-db-migration/db/migration/V2_0_3__release.sql
Labels: Study builder, cla: yes

#3207 [v2.0.3] Swagger Configuration for Auth Server API documentation
  auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/OAuthController.java
  auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserController.java
  auth-server/oauth-scim-service/src/test/java/com/google/cloud/healthcare/fdamystudies/SwaggerGeneratorTest.java
  common-modules/common-service/pom.xml
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/CommonConstants.java
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/SwaggerConfig.java
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/SwaggerParameterAnnotationPlugin.java
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/HealthController.java
  common-modules/common-tests/src/main/java/com/google/cloud/healthcare/fdamystudies/common/BaseMockIT.java
  documentation/API/auth-server/openapi.json
  participant-datastore/user-mgmt-module/user-mgmt/pom.xml
Labels: Auth server, cla: yes

#3278 [v2.0.3] Fixed issue #3182 issue logo replaced-fixed
  participant-manager/src/assets/images/branding/landing-logo-old.png
  participant-manager/src/assets/images/branding/landing-logo.png
  participant-manager/src/assets/images/landing-logo-old.png
  participant-manager/src/assets/images/landing-logo.png
Labels: cla: yes

#3279 [v2.0.3] Fixed issue-SB-webapp #3188-#3157-fixed
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
Labels: cla: yes

#3239 [v2.0.3] : Fixed issue #2929, #3149
  db-migration/study-builder-db-migration/db/migration/V2_0_3__release.sql
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/ConsentBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
  study-datastore/src/main/java/com/hphc/mystudies/bean/ReviewBean.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dto/ConsentDto.java
Labels: Study builder, cla: yes

#3282 [v2.0.3] Fixed Issue #3281: Text changes for email templates
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
  participant-manager-datastore/participant-manager-service/src/main/resources/application.properties
Labels: Participant datastore, Participant manager datastore, cla: yes

#3268 [v2.0.3] Swagger Configuration for Consent management Service API documentation
  documentation/API/participant-consent-datastore/openapi.json
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserConsentManagementController.java
  participant-datastore/consent-mgmt-module/consent-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/common/SwaggerGeneratorTest.java
Labels: cla: yes

#3270 [v2.0.3] Swagger Configuration for Enroll management Service API documentation
  documentation/API/participant-enroll-datastore/openapi.json
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/EnrollmentTokenController.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/ParticipantInformationController.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/StudyStateController.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/common/SwaggerGeneratorTest.java
Labels: cla: yes

#3266 [v2.0.3] Swagger Configuration for Response Datastore API documentation
  documentation/API/response-datastore/openapi.json
  response-datastore/response-server-service/pom.xml
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/FdaMystudiesResponseServerApplication.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/ParticipantIdController.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/ProcessActivityResponseController.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/ProcessActivityStateController.java
  response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/StudyMetadataController.java
  response-datastore/response-server-service/src/test/java/com/google/cloud/healthcare/fdamystudies/SwaggerGeneratorTest.java
Labels: cla: yes

#3286 [v2.0.3] Rollback issue 3247 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
Labels: cla: yes

#3272 [v2.0.3] Swagger Configuration for Participant Management Service API documentation
  documentation/API/participant-manager-datastore/openapi.json
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/AppController.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/ConsentController.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/LocationController.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/SiteController.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/StudyController.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserController.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileController.java
  participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/SwaggerGeneratorTest.java
Labels: Participant manager datastore, cla: yes

#3287 [v2.0.3] Email template corrected for study builder
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
Labels: cla: yes

#3288 [v2.0.3] iOS-Bug Fixes
  iOS/MyStudies/MyStudies.xcodeproj/project.pbxproj
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/OverviewImages/overviewLogo.imageset/logo1@2x.png
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/OverviewImages/overviewLogo.imageset/logo1@3x.png
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/Splash/splash.imageset/Contents.json
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/Splash/splash.imageset/splash@2x-2.jpg
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/Splash/splash.imageset/splash@2x.jpg
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/Splash/splash.imageset/splash@3x-2.jpg
  iOS/MyStudies/MyStudies/Assets/Assets.xcassets/Splash/splash.imageset/splash@3x.jpg
  iOS/MyStudies/MyStudies/Assets/LoginAssets.xcassets/LoginScreen/watchVideo.imageset/Contents.json
  iOS/MyStudies/MyStudies/Assets/LoginAssets.xcassets/LoginScreen/watchVideo.imageset/play_button1@2x.png
  iOS/MyStudies/MyStudies/Assets/LoginAssets.xcassets/LoginScreen/watchVideo.imageset/play_button1@3x.png
  iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/ConfirmationViewUI/ConfirmationViewController.swift
  iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/RegisterUI/SignUpViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourcesViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
  iOS/MyStudies/MyStudies/FDA.entitlements
  iOS/MyStudies/MyStudies/Info.plist
  iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift
  iOS/MyStudies/MyStudies/Models/StudyModel/Study.swift
  iOS/MyStudies/MyStudies/Models/UserModel/User.swift
  iOS/MyStudies/MyStudies/Utils/Helpers/Constants/Constants.swift
  iOS/MyStudies/MyStudies/Views/Cells/TableView/LoginAndRegister/SignUpTableViewCell.swift
  iOS/MyStudies/MyStudies/Views/Cells/TableView/Resource/ResourcesTableViewCell.swift
  iOS/MyStudies/ResearchKit.xcodeproj/xcuserdata/admin.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: cla: yes

#3267 [v2.0.3]Swagger Configuration for User management Service API documentation
  documentation/API/participant-user-datastore/openapi.json
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/StudiesController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserRegistrationController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserSupportController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/VerifyEmailIdController.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/SwaggerGeneratorTest.java
Labels: Participant datastore, cla: yes

#3280 [v2.0.3] Issue #562 Start time cannot be specified for activity with custom schedule
  auth-server/oauth-scim-service/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3292 [v2.0.3] Email template corrected for study builder
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
Labels: cla: yes

#3289 [v2.0.3] iOS Fixes for - #3082
  iOS/MyStudies/MyStudies/Branding/Generic/Branding.plist
  iOS/MyStudies/MyStudies/Controllers/ConsentUI/ConsentSharePdfStepViewController.swift
  iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift
  iOS/MyStudies/MyStudies/Controllers/FetalKickUI/FetalKickCounterStepViewController/FetalKickCounterStepViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/ProfileViewUI/ProfileViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/ReachoutUI/ContactUsViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/ReachoutUI/FeedBackViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/ReachoutUI/ReachoutOptionsViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/SlideMenu/LeftMenuViewController.swift
  iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
  iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/LoginUI/ForgotPasswordViewController.swift
  iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/LoginUI/SignInViewController.swift
  iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/RegisterUI/VerificationViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/QuestionStepController/TextChoiceQuestionController.swift
  iOS/MyStudies/MyStudies/Models/Activity/ActivityBuilder/ActivityBuilder.swift
  iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift
  iOS/MyStudies/MyStudies/Models/Resource/Resources.plist
  iOS/MyStudies/MyStudies/Storyboards/Base.lproj/Main.storyboard
  iOS/MyStudies/MyStudies/Storyboards/FetalKickCounter.storyboard
  iOS/MyStudies/MyStudies/Storyboards/Gateway.storyboard
  iOS/MyStudies/MyStudies/Storyboards/Login.storyboard
  iOS/MyStudies/MyStudies/Storyboards/Study.storyboard
  iOS/MyStudies/MyStudies/Utils/Helpers/Constants/Constants.swift
  iOS/MyStudies/MyStudies/Utils/Helpers/Eligibility/EligibilityStep/EligibilityBuilder.swift
  iOS/MyStudies/MyStudies/Utils/Helpers/Managers/LocalNotification.swift
  iOS/MyStudies/MyStudies/Utils/Resources/Localizable/LocalizableString.swift
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/Activities.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/AnonymousFilterData.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/ContactUs.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/FilterData.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/GatewayOverview.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/Profile.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/ResourcesUI.plist
  iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/StudyOverview.plist
  iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityActiveStep.swift
  iOS/MyStudies/MyStudies/Views/Steps/FetalKickCounterTask/FetalKickCounterTask.swift
  iOS/MyStudies/MyStudies/Views/UIViews+Additions/ComprehensionFailureUI/ComprehensionFailure.xib
  iOS/MyStudies/MyStudies/Views/UIViews+Additions/ForceUpdate/AppUpdateBlocker.xib
Labels: cla: yes

#3291 [v2.0.3] Fixed issue #3281: Text changes for email templates
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
  participant-manager-datastore/participant-manager-service/src/main/resources/application.properties
Labels: cla: yes

#3298 [v2.0.4] PM Web App Issue #3276 fixing
  participant-manager/src/app/auth/set-up-account/set-up-account.component.ts
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.ts
Labels: cla: yes

#3294 [v2.0.3] Oauth server email template update
  auth-server/oauth-scim-service/src/main/resources/application.properties
  auth-server/oauth-scim-service/src/test/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserControllerTest.java
Labels: Auth server, cla: yes

#3246 [v2.0.3] Android - fixes for #2757
  Android/app/src/main/java/com/harvard/studyappmodule/CustomActivitiesDailyDialogClass.java
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesFragment.java
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesListAdapter.java
Labels: cla: yes

#3302 Create README for db migration
  db-migration/README.md
Labels: cla: yes

#3303 [v2.0.3] Android - fixes for #3301
  Android/app/src/main/java/com/harvard/studyappmodule/consent/ConsentBuilder.java
Labels: cla: yes

#3329 [v2.0.3] DB migration script execution failure fix for Participant Datastore
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/resources/application.properties
  response-datastore/response-server-service/src/main/resources/application.properties
Labels: cla: yes

#3330 Add db-migration link in deployment docs
  deployment/README.md
Labels: cla: yes

#3328 Update README.md
  db-migration/README.md
Labels: cla: yes

#3337 README.md for API documentation
  documentation/API/README.md
Labels: cla: yes

#3336 Add 2.0.3 to What's New
  documentation/whats-new.md
Labels: cla: yes

#3427 Issue #3409 build failure for all services fix [master]
  .github/workflows/build-auth-server.yml
  .github/workflows/build-participant-consent-datastore.yml
  .github/workflows/build-participant-enroll-datastore.yml
  .github/workflows/build-participant-manager-datastore.yml
  .github/workflows/build-participant-user-datastore.yml
  .github/workflows/build-response-datastore.yml
  .github/workflows/build-studybuilder.yml
  auth-server/oauth-scim-service/pom.xml
  common-modules/common-service/pom.xml
  common-modules/common-tests/pom.xml
  participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
  participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
  participant-datastore/user-mgmt-module/user-mgmt/pom.xml
  participant-manager-datastore/participant-manager-service/pom.xml
  response-datastore/response-server-service/pom.xml
  study-builder/Dockerfile
  study-builder/cloudbuild.yaml
  study-builder/fdahpStudyDesigner/pom.xml
  study-datastore/Dockerfile
  study-datastore/cloudbuild.yaml
  study-datastore/pom.xml
Labels: Blocker, cla: yes

#3417 APNs Upgrade to newer HTTP/2 protocol
  participant-datastore/user-mgmt-module/tf-deployment.yaml
  participant-datastore/user-mgmt-module/user-mgmt/pom.xml
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/FcmPushNotificationResponse.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudiesServicesImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
  participant-datastore/user-mgmt-module/user-mgmt/src/test/resources/data.sql
  participant-datastore/user-mgmt-module/variables.env
Labels: Blocker, cla: yes
