Repository GoogleCloudPlatform/fda-mystudies, pull requests merged in 2021-05, with the labels that each got.

#3528 [v2.0.5] Fixed issue #3527
  iOS/MyStudies/MyStudies.xcodeproj/project.pbxproj
Labels: cla: yes

#3523 [v2.0.5] iOS-Fixed issue #1905, #355
  iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/GatewayOverviewUI/PageViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyOverviewPageViewControllerFirst.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyOverviewViewControllerSecond.swift
  iOS/MyStudies/MyStudies/Default.xcconfig
  iOS/MyStudies/MyStudies/Storyboards/Study.storyboard
  iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityStepResultModel/ActivityStepResult.swift
  iOS/MyStudies/Podfile
Labels: cla: yes

#3520 [v2.0.5] Fixed issue #3494 #3505
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/header.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
Labels: cla: yes

#3518 [v2.0.5] - Fixed Issue #3515 #3504
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
Labels: Study builder, cla: yes

#3517 [v2.0.5] Fixed issue #3503
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: Study builder, cla: yes

#3476 [v2.0.5] Fixed issue [SB] Use the proper text case for all the dropdown values #3366
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3452 [V2.0.5] Android - #355
  Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoPagerAdapter.java
  Android/app/src/main/res/layout/study_info_item1.xml
  Android/app/src/main/res/layout/study_info_item2.xml
Labels: cla: yes

#3538 Update mystudies.hcl
  deployment/mystudies.hcl
Labels: Deployment, cla: yes

#3539 2.0.5 documentation update
  deployment/README.md
  documentation/whats-new.md
Labels: cla: yes

#3516 [v2.0.5] Fixed issue #3492 #3176
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
Labels: Study builder, cla: yes

#3535 [v2.0.5] - Fixed Issue #3383-#3386
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js
Labels: cla: yes

#3533 [v2.0.5] Fixed issue #3530
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3534 [v2.0.5] - Fixed Issue #3529 #3532
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
Labels: Study builder, cla: yes

#3544 [v2.0.5] Fixed Issue #3386-#3543
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3545 [v2.0.5]Wrong Error Message Displayed due to incorrect HTTP Status code
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ErrorCode.java
Labels: cla: yes

#3548 [v2.0.5] iOS-Fixed issue #3424, #3537, #3319
  iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourcesViewController.swift
  iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
  iOS/MyStudies/MyStudies/Networking/APIs/UserServices.swift
  iOS/MyStudies/MyStudies/Utils/Extension/String+Extensions.swift
Labels: cla: yes

#3557 [v2.0.5] Fixed issue #3549
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bean/StudyListBean.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAOImpl.java
Labels: cla: yes

#3552 [v2.0.5] iOS-Fixed issue #3319
  iOS/MyStudies/MyStudies/Views/Cells/TableView/Activity/ActivitiesTableViewCell.swift
Labels: cla: yes

#3553 [v2.0.5] issue #3546 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
Labels: Study builder, cla: yes

#3554 [v2.0.5] Fixed issue #3550
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: Study builder, cla: yes

#3560 [v2.0.5] - Fixed Issue #3547
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
Labels: cla: yes

#3571 [v2.0.5] - Fixed Issue - #3564
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: cla: yes

#3569 [v2.0.5] Fixed issue #3508
  db-migration/study-builder-db-migration/db/migration/V2_0_5__release.sql
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/NotificationBO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
Labels: cla: yes

#3565 [v2.0.5] Fixed issue #3555
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
Labels: Study builder, cla: yes

#3570 [v2.0.5] Fixed issue #3563
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/ActiveTaskBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
Labels: cla: yes

#3574 [v2.0.5] Fixed issue #3572
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
Labels: cla: yes

#3577 Fix #3575 - Add Cloud Build Shared VPC deployment instructions
  deployment/README.md
Labels: cla: yes

#3583 Super Admin login issue fix for RC 2.0.5
  auth-server/oauth-scim-service/logs/spring.log.2021-02-11.0.gz
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/UserAccountStatus.java
Labels: cla: yes

#3604 [v2.0.6] Fixed UI issues [SB] #3586 and [Auth server] #3506
  auth-server/oauth-scim-service/src/main/resources/static/css/style.css
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
Labels: cla: yes

#3594 [v2.0.6] Fixed Issue #3582 #3559
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: Study builder, cla: yes

#3605 [v2.0.6] Fixed issue #3581
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
Labels: Study builder, cla: yes

#3466 [v2.0.6] Fixed Issue #295
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/CustomMultipartFile.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/ImageUtility.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: Study builder, cla: yes

#3597 [v2.0.6] Issue #3558 Fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
Labels: cla: yes

#3599 [v2.0.6] Issue #3585 Fixes
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/test/resources/Email_Import_Template.xlsx
  participant-manager-datastore/participant-manager-service/src/test/resources/Email_Import_Template_Invalid_Emails.xlsx
  participant-manager-datastore/participant-manager-service/src/test/resources/Email_Import_Template_bad_header.xlsx
  participant-manager/src/assets/Email_Import_Template.xlsx
Labels: cla: yes

#3617 [v2.0.6] Fixed issue #940 [study builder] assets should be stored in a hierarchy
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/CommonConstants.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AppPropertyConfig.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/util/ParticipantManagerUtil.java
  participant-manager-datastore/participant-manager-service/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/StudyBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/MoveCloudStorageSchedulerService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/ApplicationInitializer.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/ApplicationContext.xml
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataConstants.java
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java
  study-datastore/src/main/resources/application.properties
Labels: cla: yes

#3625 [v2.0.6] Issue #3621 #3615 #3596
  participant-manager/src/app/auth/set-up-account/set-up-account.component.html
  participant-manager/src/app/auth/set-up-account/set-up-account.component.scss
  participant-manager/src/app/auth/set-up-account/set-up-account.component.ts
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
Labels: cla: yes

#3623 [v2.0.6] Issue #1288 #3526 #3540 #3579 #3601 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-datastore/pom.xml
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
Labels: cla: yes

#3624 [v2.0.6] Fixed issue #3606 [SB] Comprehension test > 'Minimum score needed to pass the test' field should be mandatory field
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
Labels: cla: yes

#3613 [v2.0.6] Fixed issue #3600 [SB] View mode of the study > Overview screen > User is able to edit the 'Description' field in view mode
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
Labels: cla: yes

#3610 [v2.0.6] Fixed issue [Mobile] Studies are not displaying in Study list screen in mobile #3609
  study-datastore/pom.xml
Labels: cla: yes

#3611 [v2.0.6] Fixed Issue #3608 #3612
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3619 [v2.0.6] Issue 3551 Fixes
  db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql
Labels: cla: yes
