Repository GoogleCloudPlatform/fda-mystudies, pull requests merged in 2021-04, with the labels that each got.

#3425 [v2.0.4] Issue 3418 fixes
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserConsentManagementController.java
Labels: Participant datastore, cla: yes

#3414 [v2.0.4] Issue 3398 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
Labels: Study builder, cla: yes

#3400 [v2.0.4] Issue 3380 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
Labels: Study builder, cla: yes

#3399 [v2.0.4] Issue 3378 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
Labels: Study builder, cla: yes

#3368 [v2.0.4] Issue 3358 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
Labels: Study builder, cla: yes

#3349 [v2.0.4] Issue 954 and 3324 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
Labels: Study builder, cla: yes

#3344 [v2.0.4] Issue 3306 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
Labels: Study builder, cla: yes

#3343 [v2.0.4] Issue 3277 fixes
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
Labels: Study builder, cla: yes

#3413 [v2.0.4] Fixed issue #3366 [SB] Use the proper text case for all the dropdown values
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/checklist.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css
  study-builder/sqlscript/version_info_script.sql
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataConstants.java
Labels: cla: yes

#3419 [v2.0.4] Fixed issue #3173 and #3396
  auth-server/oauth-scim-service/src/main/resources/static/css/style.css
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ErrorCode.java
  deployment/scripts/create_participant_manager_superadmin.sh
  deployment/scripts/create_study_builder_superadmin.sh
  participant-datastore/sqlscript/create_superadmin.sh
  participant-manager/src/app/auth/login-callback/login-callback.component.ts
  study-builder/sqlscript/create_superadmin.sh
Labels: cla: yes

#3429 [v2.0.4] Fixed issue #3391 [SB] Active task > Schedule tab > Anchor date based > Error message is not displayed for the following scenario
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: cla: yes

#3426 [v2.0.4]Issue #3409 fix for build failure for all module
  .github/workflows/build-auth-server.yml
  .github/workflows/build-participant-consent-datastore.yml
  .github/workflows/build-participant-enroll-datastore.yml
  .github/workflows/build-participant-manager-datastore.yml
  .github/workflows/build-participant-user-datastore.yml
  .github/workflows/build-response-datastore.yml
  .github/workflows/build-studybuilder.yml
  auth-server/oauth-scim-service/pom.xml
  common-modules/common-service/pom.xml
  common-modules/common-tests/pom.xml
  participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
  participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
  participant-datastore/user-mgmt-module/user-mgmt/pom.xml
  participant-manager-datastore/participant-manager-service/pom.xml
  response-datastore/response-server-service/pom.xml
  study-builder/Dockerfile
  study-builder/cloudbuild.yaml
  study-builder/fdahpStudyDesigner/pom.xml
  study-datastore/Dockerfile
  study-datastore/cloudbuild.yaml
  study-datastore/pom.xml
Labels: cla: yes

#3407 [v2.0.4] [Participant Datastore] APNs upgrade issue #3364 fix
  participant-datastore/user-mgmt-module/tf-deployment.yaml
  participant-datastore/user-mgmt-module/user-mgmt/pom.xml
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/FcmPushNotificationResponse.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudiesServicesImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
  participant-datastore/user-mgmt-module/user-mgmt/src/test/resources/data.sql
  participant-datastore/user-mgmt-module/variables.env
Labels: cla: yes

#3345 [v2.0.4] Participant Manager Default super admin creation script issue fix
  deployment/scripts/create_participant_manager_superadmin.sh
Labels: cla: yes

#3351 [v2.0.4] Fixed issue #3295 and #3313
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/FDASchedulerService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
Labels: Study builder, cla: yes

#3372 [v2.0.4] Fixed Issue #3299 #3367
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Study builder, cla: yes

#3415 [v2.0.4] Fixed issue #3406 #3412
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/UserStatus.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: Participant manager datastore, Study builder, cla: yes

#3421 [V2.0.4] PM Web app Issue #3342 fixed Table columns alignment.
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
Labels: Participant manager, cla: yes

#3397 [V2.0.4] PM-Web-Issue #3387 UI fixed with study and sites status indicator.
  participant-manager/src/assets/css/root.scss
Labels: Participant manager, cla: yes

#3393 [V2.0.4] fixed #3341 UI issue in sites.
  participant-manager/src/assets/css/root.scss
Labels: Participant manager, cla: yes

#3371 [V2.0.4] Issue #3340 fixing
  participant-manager/src/app/site-coordinator/sites/add-email/add-email.component.html
Labels: Participant manager, cla: yes

#3362 [V2.0.4] Issue #3016 fixes
  participant-manager/src/app/auth/login/login.component.ts
Labels: Participant manager, cla: yes

#3355 [V2.0.4] Issue #2981 fixes
  participant-manager/src/app/site-coordinator/apps/app-list/app-list.component.html
  participant-manager/src/app/site-coordinator/sites/site-list/site-list.component.html
  participant-manager/src/app/site-coordinator/studies/study-list/study-list.component.html
Labels: Participant manager, cla: yes

#3348 [v2.0.4] Fixed Issue #2996 #3317
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3347 [v2.0.4] Fixed Issue #3283 #3293
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/tf-deployment.yaml
  study-builder/variables.env
Labels: cla: yes

#3354 [v2.0.4] Fixed Issue #1798
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/ApplicationPropertyConfiguration.java
  participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/CommonDaoImpl.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/EnrollmentTokenController.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/CommonDaoImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/config/ApplicationPropertyConfiguration.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/CommonDaoImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/UserProfileManagementDaoImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/CommonServiceImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
Labels: cla: yes

#3350 [v2.0.4] Fixed issue #3273
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ParticipantManagerEvent.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/ManageUserServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserProfileServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/AdminUsersAccountScheduledTaskTest.java
  participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserControllerTest.java
  participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileControllerTest.java
Labels: Participant manager datastore, cla: yes

#3416 [v2.0.4] Fixed issue #3381
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
Labels: Study builder, cla: yes

#3389 [v2.0.4] Fixed Issue #3375 #3382
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
Labels: Study builder, cla: yes

#3346 [v2.0.4] Issues #3290 and #3247 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
Labels: Study builder, cla: yes

#3401 [v2.0.4] Fixed Issue #3166 #2644 #3394 and #3405
  auth-server/oauth-scim-service/src/main/resources/static/js/jquery.min.js
  auth-server/oauth-scim-service/src/main/resources/templates/autoLogin.html
  auth-server/oauth-scim-service/src/main/resources/templates/consent.html
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/NotificationBO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/NotificationController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAO.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/FDASchedulerService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/NotificationServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
Labels: Study builder, cla: yes

#3388 [v2.0.4] Fixed Issue #3365
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibiltyTest.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
Labels: Study builder, cla: yes

#3356 [v2.0.4] Android - #3318
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesListAdapter.java
Labels: cla: yes

#3363 [V2.0.4] Android - #3311
  Android/app/src/main/java/com/harvard/studyappmodule/SurveyDashboardFragment.java
Labels: cla: yes

#3353 [v2.0.4] Fixed issue #3333 #3285
  auth-server/oauth-scim-service/src/main/resources/application.properties
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3402 [v2.0.4] Fixed issue #3322 and #3379
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/EnrollmentTokenDaoImpl.java
  participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/resources/data.sql
Labels: Participant datastore, Study builder, cla: yes

#3408 [v2.0.4] Fixed issue #3300
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Labels: cla: yes

#3431 V2.0,4 issue #3334 fixing
  participant-manager/src/app/site-coordinator/user/user-details/user-details.component.html
Labels: cla: yes

#3432 [v2.0.4]Fixed issues-#3376-#3377-#3384-#3385
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css
Labels: cla: yes

#3411 [v2.0.4] Fixed issue #3255
  participant-manager/src/app/auth/set-up-account/set-up-account.component.html
  participant-manager/src/app/auth/set-up-account/set-up-account.component.scss
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
  participant-manager/src/app/site-coordinator/account/change-password/change-password.component.scss
  participant-manager/src/assets/css/root.scss
  participant-manager/src/assets/css/utilities.scss
  participant-manager/src/styles.scss
Labels: cla: yes

#3437 [v2.0.4] Fixed SB - issues ##3332 and ##3323
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
Labels: cla: yes

#3436 [v2.0.4] Fixed issues #3433 and #3422
  auth-server/oauth-scim-service/src/main/resources/application.properties
  auth-server/oauth-scim-service/src/main/resources/static/css/style.css
Labels: cla: yes

#3434 [v2.0.5] Fixed Issue #3373 #3374
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyActiveTasksControllerTest.java
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyControllerTest.java
Labels: Study builder, cla: yes

#3446 Release 2.0.4
  deployment/README.md
  documentation/whats-new.md
Labels: cla: yes

#3369 [V2.0.5] Android - #3357
  Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ValuePickerQuestion.java
Labels: cla: yes

#3447 [v2.0.5] PM Web app issue #3435 fixing
  participant-manager/src/app/site-coordinator/apps/app-details/app-details.component.html
  participant-manager/src/app/site-coordinator/apps/app-list/app-list.component.html
  participant-manager/src/app/site-coordinator/location/location-list/location-list.component.html
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
  participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.html
  participant-manager/src/app/site-coordinator/sites/site-list/site-list.component.html
  participant-manager/src/app/site-coordinator/studies/study-details/study-details.component.html
  participant-manager/src/app/site-coordinator/studies/study-list/study-list.component.html
  participant-manager/src/app/site-coordinator/user/user-details/user-details.component.html
  participant-manager/src/app/site-coordinator/user/user-list/user-list.component.html
Labels: Participant manager, cla: yes

#3449 [v2.0.5] Fixed issue #3448
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
Labels: cla: yes

#3457 [v2.0.5] Fixed issue #3456 [SB][QA] E-Consent Steps screen > Save/Cancel/Mark as Completed buttons are non functional
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
Labels: cla: yes

#3455 [v2.0.5] Fixed Issue #3442
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
Labels: Study builder, cla: yes

#3450 [V2.0.5] Android - #3423
  Android/app/src/main/java/com/harvard/studyappmodule/custom/activetask/Tappingactivity.java
Labels: cla: yes

#3454 [V2.0.5] Android - #3420
  Android/app/src/main/res/layout/activity_comprehension_failure.xml
  Android/app/src/main/res/layout/activity_comprehension_success.xml
  Android/app/src/main/res/layout/activity_consent_completed.xml
  Android/app/src/main/res/layout/activity_survey_complete.xml
  Android/app/src/main/res/layout/rsb_step_layout_consent_doc.xml
  Android/app/src/main/res/layout/rsb_step_layout_instruction_custom.xml
Labels: cla: yes

#3370 [V2.0.5] Android - #3352
  Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ScaleTextQuestion.java
  Android/app/src/main/res/layout/checkboxdesc.xml
  Android/app/src/main/res/layout/rsb_step_layout_consent_visual.xml
  Android/app/src/main/res/layout/seekbar_text_vertical_layout.xml
Labels: cla: yes

#3360 [v2.0.5] Fixed issue #355
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
Labels: Study builder, cla: yes

#3469 [v2.0.5] Issue 3467 fixes
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/EmailNotification.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/Mail.java
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/common/BaseMockIT.java
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/config/WebAppTestConfig.java
Labels: cla: yes

#3460 [v2.0.5] Fixed Issue #3453
  participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/Mail.java
  study-builder/fdahpStudyDesigner/src/main/resources/application.properties
Labels: cla: yes

#3463 [v2.0.5] Pm web issue #3443 fixing
  participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
Labels: Participant manager, cla: yes

#3493 [v2.0.5] Pm web app issue 3477 fixing
  participant-manager/src/assets/css/root.scss
Labels: Participant manager, cla: yes

#3470 [v2.0.5] Issue 1825 and 2868 fixes
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/AuthInfoRepository.java
  participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/UserProfileManagementDaoImpl.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileControllerTest.java
  participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/testutils/Constants.java
Labels: cla: yes

#3458 [v2.0.5] Issue 3438 fixes
  auth-server/oauth-scim-service/pom.xml
  participant-manager-datastore/participant-manager-service/pom.xml
  participant-manager/package-lock.json
  participant-manager/package.json
  response-datastore/response-server-service/pom.xml
  study-builder/fdahpStudyDesigner/pom.xml
  study-datastore/pom.xml
Labels: cla: yes

#3502 [v2.0.5]Fixed issue #3383
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/checklist.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibiltyTest.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js
Labels: cla: yes

#3461 [v2.0.5] Fixed Issue #3297
  common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/CommonConstants.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/config/AppPropertyConfig.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/mapper/StudyMapper.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
  participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/util/ParticipantManagerUtil.java
  participant-manager-datastore/participant-manager-service/src/main/resources/application.properties
  participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/SiteControllerTest.java
  participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/StudyControllerTest.java
  participant-manager-datastore/participant-manager-service/src/test/resources/application-mockit.properties
  participant-manager-datastore/tf-deployment.yaml
  participant-manager-datastore/variables.env
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/QuestionReponseTypeBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/QuestionResponseSubTypeBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/StudyPageBo.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
  study-datastore/pom.xml
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataConstants.java
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java
  study-datastore/src/main/resources/application.properties
Labels: cla: yes

#3507 [v2.0.5] Fixed Issue #355
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
Labels: Study builder, cla: yes

#3486 [v2.0.5] Fixed issue #3478
  study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
Labels: cla: yes

#3511 [v2.0.5] - Fixed Issue #499 in Study datastore
  study-datastore/pom.xml
  study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/AppMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/DashboardMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
  study-datastore/src/main/java/com/hphc/mystudies/integration/ActivityMetaDataOrchestration.java
  study-datastore/src/main/java/com/hphc/mystudies/integration/AppMetaDataOrchestration.java
  study-datastore/src/main/java/com/hphc/mystudies/integration/DashboardMetaDataOrchestration.java
  study-datastore/src/main/java/com/hphc/mystudies/integration/StudyMetaDataOrchestration.java
  study-datastore/src/main/java/com/hphc/mystudies/service/AuditEventService.java
  study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java
  study-datastore/src/main/java/com/hphc/mystudies/util/HibernateUtil.java
  study-datastore/src/main/java/com/hphc/mystudies/util/PropertiesUtil.java
  study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java
  study-datastore/src/main/java/com/hphc/mystudies/web/servlet/AuthenticationService.java
  study-datastore/src/main/java/com/hphc/mystudies/web/servlet/RestAuthenticationFilter.java
  study-datastore/src/main/java/com/hphc/mystudies/web/servlet/StudyMetaDataController.java
Labels: cla: yes

#3513 [v2.0.5] - Fixed issue #499 in Study Builder
  study-builder/fdahpStudyDesigner/pom.xml
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/PlaceholderReplacer.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/DashBoardAndProfileController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/LoginController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/NotificationController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/UsersController.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/FDASchedulerService.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/ApplicationInitializer.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/CrossScriptingFilter.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/EmailNotification.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerPreHandlerInterceptor.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/LimitLoginAuthenticationProvider.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/Mail.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/PropertiesUtil.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/RequestWrapper.java
  study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/common/BaseMockIT.java
Labels: cla: yes

#3514 [v-2.0.5] - Fixed issue #499
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/AuditLogDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/DashBoardAndProfileDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/LoginDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAOImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/AuditEventServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/DashBoardAndProfileServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/NotificationServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
  study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
Labels: cla: yes
